using TMPro;
using UnityEditor.PackageManager;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.SceneManagement;

public enum UIState
{
    Default,
    Start,
    Pause,
    ControlMethodSelection,
    Credits,
}

public class GUIManager : MonoBehaviour
{
    [SerializeField] private GameObject _pauseScreen;
    [SerializeField] private GameObject _startScreen;
    [SerializeField] private GameObject _controls;
    [SerializeField] private string _mainMenuSceneName;
    //[SerializeField] private TMP_Text _infoText;
    private PlayerActionsAutoGenerated _playerActions;
    private UIState _currentState;
    private UIState _storedUIState = UIState.Default;


    public void Awake()
    {
        //_playerActions = new PlayerActionsAutoGenerated();
    }


    public void Start()
    {
        DeactivateScreens();
        _currentState = UIState.Start;
        SwitchState(_currentState);
        //InputManager.Instance.Actions.UI.Interact.performed += DisplayPauseScreen;
    }


    void OnEnable()
    {

        

        //Events.SubtitlesSkip.Subscribe(SubtitlesSkip);
        //Events.SubtitlesStop.Subscribe(OnSubtitlesStopped);  // FIXED

        SetupNavigationForWebGL();
    }

    void OnDisable()
    {

        if (InputManager.Instance != null)
        {
            //InputManager.Instance.Actions.UI.Interact.performed -= DisplayPauseScreen;
        }

        //Events.SubtitlesSkip.Unsubscribe(SubtitlesSkip);
        //Events.SubtitlesStop.Unsubscribe(OnSubtitlesStopped); // FIXED
    }

    //private void EnableMouse()
    //{ 
    //    Cursor.lockState = CursorLockMode.None;
    //}

    //private void DisableMouse()
    //{
    //    Cursor.lockState = CursorLockMode.Locked;
    //}

    void SwitchState(UIState newState)
    {
        switch (newState)
        {

            case UIState.Pause:
                Pause();
                _pauseScreen.SetActive(true);
                //EventSystem.current.SetSelectedGameObject(_defaultButtonReturn);
                break;
            case UIState.ControlMethodSelection:
                _storedUIState = _currentState;
                Pause();
                _controls.SetActive(true);
                //EventSystem.current.SetSelectedGameObject(_defaultButtonControls);
                break;
            //case UIState.Credits:
            //    _storedUIState = _currentState;
            //    EnableMouse();
            //    Pause();
            //    _creditsScreen.SetActive(true);
            //    //EventSystem.current.SetSelectedGameObject(_defaultButtonCredits);
            //    break;
            case UIState.Start:
                InputManager.Instance.SwitchToUI();
                Pause();
                _startScreen.SetActive(true);
                //EventSystem.current.SetSelectedGameObject(_defaultButtonStart);
                break;


            default:

                Unpause();
                break;
        }
        _currentState = newState;
    }

    void Pause()
    {
        Time.timeScale = 0;
        AudioListener.pause = true;
    }

    void Unpause()
    {
        Time.timeScale = 1;
        AudioListener.pause = false;
        InputManager.Instance.SwitchToPlayer();
    }

    public void DisplayPauseScreen(InputAction.CallbackContext context)
    {
        if (CheckForOpenScreens() == false)
        {
            DeactivateScreens();
            SwitchState(UIState.Pause);
        }
    }

    public void DisplayPauseScreen()
    {
        if (CheckForOpenScreens() == false)
        {
            DeactivateScreens();
            SwitchState(UIState.Pause);
        }
    }

    public void DisplayControlMethodScreen()
    {
        DeactivateScreens();
        SwitchState(UIState.ControlMethodSelection);
    }

    public void DisplayCreditsScreen()
    {
        DeactivateScreens();
        SwitchState(UIState.Credits);
    }

    private bool CheckForOpenScreens()
    {
        if (_startScreen.activeSelf == true || _pauseScreen.activeSelf == true || _controls.activeSelf == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public void DeactivateScreens()
    {
        //DisableMouse();
        Unpause();
        _startScreen.SetActive(false);
        _pauseScreen.SetActive(false);
        _controls.SetActive(false);

        if (_storedUIState != UIState.Default)
        {
            SwitchState(_storedUIState);
            _storedUIState = UIState.Default;
        }

    }

    public void LoadMainMenu()
    {
        SceneManager.LoadScene(_mainMenuSceneName);
    }

    private void SetupNavigationForWebGL()
    {
        // This is required to rectify a bug in WebGL deployments where up and down does not work on GUI screens
        // Note: Not currently working in this build.  Believe because we are still using old input.  Further research required.
        InputBinding binding = new InputBinding()
        {
            path = "<Gamepad>/leftStick",
            processors = "webglnavigation"
        };

        //defaultNavigateInputActionReference.action.AddBinding(binding);
    }

}
