using UnityEngine;

public class InputManager : MonoBehaviour
{
    public static InputManager Instance { get; private set; }
    public PlayerActionsAutoGenerated Actions { get; private set; }

    void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(gameObject);

        Actions = new PlayerActionsAutoGenerated();
        Actions.UI.Enable(); // start in Player mode
    }

    public void SwitchToPlayer()
    {
        Actions.UI.Disable();
        Actions.Player.Enable();
    }

    public void SwitchToUI()
    {
        Actions.Player.Disable();
        Actions.UI.Enable();
    }
}
