using UnityEngine;

public enum GameInputMode
{
    MainGame,
    ReactionGame,
    BreathingGame,
    UI
}

public class InputManager : MonoBehaviour
{
    public static InputManager Instance { get; private set; }

    public PlayerActionsAutoGenerated Actions { get; private set; }
    public GameInputMode CurrentMode { get; private set; }

    private void Awake()
    {
        Instance = this;

        Actions = new PlayerActionsAutoGenerated();

        Actions.UI.Enable();
        CurrentMode = GameInputMode.UI;
    }

    private void OnDestroy()
    {
        Actions?.Dispose();
    }

    public void SwitchToMainGame()
    {
        DisableMouse();

        Actions.Disable();
        Actions.MainGame.Enable();

        GamePause.SetMode(PauseMode.None);
        CurrentMode = GameInputMode.MainGame;

        Debug.Log("GameInput Mode: " + CurrentMode);
    }

    public void SwitchToReactionGame()
    {
        DisableMouse();

        Actions.Disable();
        Actions.ReactionGame.Enable();

        GamePause.SetMode(PauseMode.WorldOnly);
        CurrentMode = GameInputMode.ReactionGame;

        Debug.Log("GameInput Mode: " + CurrentMode);
    }

    public void SwitchToBreathingGame()
    {
        EnableMouse();

        Actions.Disable();
        Actions.BreathingGame.Enable();

        GamePause.SetMode(PauseMode.WorldOnly);
        CurrentMode = GameInputMode.BreathingGame;

        Debug.Log("GameInput Mode: " + CurrentMode);
    }

    public void SwitchToUI()
    {
        EnableMouse();

        Actions.Disable();
        Actions.UI.Enable();

        GamePause.SetMode(PauseMode.Hard);
        CurrentMode = GameInputMode.UI;

        Debug.Log("GameInput Mode: " + CurrentMode);
    }

    private void DisableMouse()
    {
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
    }

    private void EnableMouse()
    {
        Cursor.visible = true;
        Cursor.lockState = CursorLockMode.None;
    }
}
