using UnityEngine;

public enum GameInputMode
{
    MainGame,
    ReactionGame,
    UI
}
public class InputManager : MonoBehaviour
{
    public static InputManager Instance { get; private set; }
    public PlayerActionsAutoGenerated Actions { get; private set; }

    public GameInputMode CurrentMode { get; private set; }

    void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(gameObject);

        Actions = new PlayerActionsAutoGenerated();
        Actions.UI.Enable(); // start in Player mode
    }

    public void SwitchToMainGame()
    {
        DisableMouse();
        Actions.UI.Disable();
        Actions.ReactionGame.Disable();
        Actions.BreathingGame.Disable();
        Actions.MainGame.Enable();
        CurrentMode = GameInputMode.MainGame;
    }

    public void SwitchToReactionGame()
    {
        DisableMouse();
        Actions.UI.Disable();
        Actions.MainGame.Disable();
        Actions.BreathingGame.Disable();
        Actions.ReactionGame.Enable();
        CurrentMode = GameInputMode.ReactionGame;
    }

    public void SwitchToUI()
    {
        EnableMouse();
        Actions.MainGame.Disable();
        Actions.ReactionGame.Disable();
        Actions.BreathingGame.Disable();
        Actions.UI.Enable();
        CurrentMode = GameInputMode.UI;
    }

    public void SwitchToBreathingGame()
    {
        EnableMouse();
        Actions.MainGame.Disable();
        Actions.ReactionGame.Disable();
        Actions.UI.Disable();
        Actions.BreathingGame.Enable();
        CurrentMode = GameInputMode.UI;
    }

    void DisableMouse()
    {
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
    }

    void EnableMouse()
    {
        Cursor.visible = true;
        Cursor.lockState = CursorLockMode.None;
    }

}
